---
- name: Add nginx package
  tags: package
  apt:
    pkg: nginx
    state: installed
    update_cache: true

- name: copy http config
  copy: src=http.conf dest=/etc/nginx/sites-available/http.conf owner=root group=root mode=0755

- name: sym link file to sites enabled
  become: yes
  file:
    src: /etc/nginx/sites-available/http.conf
    dest: /etc/nginx/sites-enabled/http.conf
    state: link
    # command: ln -sf /etc/nginx/sites-available/http.conf /etc/nginx/sites-enabled/http.conf
    
- name: restart nginx
  become: yes
  service:
    name: nginx
    state: reloaded
